!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 10.0
        y: 0
        z: 10.0
      - !Vector3
        x: 10.0
        y: 0
        z: 20.0
      - !Vector3
        x: 10.0
        y: 0
        z: 30.0
      - !Vector3
        x: 20.0
        y: 0
        z: 10.0
      - !Vector3
        x: 20.0
        y: 0
        z: 20.0
      - !Vector3
        x: 20.0
        y: 0
        z: 30.0
      - !Vector3
        x: 30.0
        y: 0
        z: 10.0
      - !Vector3
        x: 30.0
        y: 0
        z: 20.0
      - !Vector3
        x: 30.0
        y: 0
        z: 30.0
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 10.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 30.0
        y: 0
        z: 4.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 10.0
        y: 0
        z: 15.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 15.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 20.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 4.0
        y: 0
        z: 30.0
      - !Vector3
        x: 10.0
        y: 0
        z: 25.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 30.0
        y: 0
        z: 25.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 36.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 16.945067857775108
        y: 0
        z: 14.551467460842808
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 2.8271459651325315
        y: 0
        z: 17.343077528536693
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 11.044340684298513
        y: 0
        z: 34.72295978007426
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
