!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 10.0
        y: 0
        z: 10.0
      - !Vector3
        x: 10.0
        y: 0
        z: 20.0
      - !Vector3
        x: 10.0
        y: 0
        z: 30.0
      - !Vector3
        x: 20.0
        y: 0
        z: 10.0
      - !Vector3
        x: 20.0
        y: 0
        z: 20.0
      - !Vector3
        x: 20.0
        y: 0
        z: 30.0
      - !Vector3
        x: 30.0
        y: 0
        z: 10.0
      - !Vector3
        x: 30.0
        y: 0
        z: 20.0
      - !Vector3
        x: 30.0
        y: 0
        z: 30.0
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 4.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 36.0
        y: 0
        z: 10.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 10.0
        y: 0
        z: 15.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 20.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 20.0
      - !Vector3
        x: 30.0
        y: 0
        z: 15.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 10.0
        y: 0
        z: 25.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 30.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 30.0
        y: 0
        z: 36.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 27.412718617916862
        y: 0
        z: 5.815671239917454
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 25.34422619169326
        y: 0
        z: 25.44498079729844
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 33.51337705331112
        y: 0
        z: 17.729480326357617
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
