!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 8.0
        y: 0
        z: 8.0
      - !Vector3
        x: 8.0
        y: 0
        z: 16.0
      - !Vector3
        x: 8.0
        y: 0
        z: 24.0
      - !Vector3
        x: 8.0
        y: 0
        z: 32.0
      - !Vector3
        x: 16.0
        y: 0
        z: 8.0
      - !Vector3
        x: 16.0
        y: 0
        z: 16.0
      - !Vector3
        x: 16.0
        y: 0
        z: 24.0
      - !Vector3
        x: 16.0
        y: 0
        z: 32.0
      - !Vector3
        x: 24.0
        y: 0
        z: 8.0
      - !Vector3
        x: 24.0
        y: 0
        z: 16.0
      - !Vector3
        x: 24.0
        y: 0
        z: 24.0
      - !Vector3
        x: 24.0
        y: 0
        z: 32.0
      - !Vector3
        x: 32.0
        y: 0
        z: 8.0
      - !Vector3
        x: 32.0
        y: 0
        z: 16.0
      - !Vector3
        x: 32.0
        y: 0
        z: 24.0
      - !Vector3
        x: 32.0
        y: 0
        z: 32.0
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 3.0
        y: 0
        z: 8.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 8.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 8.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 8.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 16.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 16.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 32.0
        y: 0
        z: 12.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 3.0
        y: 0
        z: 24.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 24.0
      - !Vector3
        x: 24.0
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 32.0
        y: 0
        z: 20.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 32.0
      - !Vector3
        x: 16.0
        y: 0
        z: 28.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 32.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 32.0
      - !Vector3
        x: 32.0
        y: 0
        z: 28.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 19.057305700877
        y: 0
        z: 35.03412189938554
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 3.2033521841790007
        y: 0
        z: 35.53359178479769
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 4.260116774838404
        y: 0
        z: 30.9809512672248
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
