!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 3.5
        y: 0
        z: 3.5
      - !Vector3
        x: 3.5
        y: 0
        z: 10.0
      - !Vector3
        x: 10.0
        y: 0
        z: 3.5
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 2
        z: 7.0
      - !Vector3
        x: 7.0
        y: 2
        z: 6
      - !Vector3
        x: 6
        y: 2
        z: 7.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 3.5
      - !Vector3
        x: 20.0
        y: 0
        z: 3.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 2
        z: 7.0
      - !Vector3
        x: 6
        y: 2
        z: 7.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 3.5
      - !Vector3
        x: 25.0
        y: 0
        z: 10.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 2
        z: 7.0
      - !Vector3
        x: 4.0
        y: 2
        z: 6
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 36.5
        y: 0
        z: 3.5
      - !Vector3
        x: 36.5
        y: 0
        z: 10.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 2
        z: 7.0
      - !Vector3
        x: 7.0
        y: 2
        z: 6
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 3.5
        y: 0
        z: 15.0
      - !Vector3
        x: 10.0
        y: 0
        z: 15.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 2
        z: 4.0
      - !Vector3
        x: 6
        y: 2
        z: 4.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 15.0
      - !Vector3
        x: 15.0
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 2
        z: 4.0
      - !Vector3
        x: 4.0
        y: 2
        z: 6
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 15.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 2
        z: 4.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 36.5
        y: 0
        z: 15.0
      - !Vector3
        x: 36.5
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 2
        z: 4.0
      - !Vector3
        x: 7.0
        y: 2
        z: 6
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 3.5
        y: 0
        z: 25.0
      - !Vector3
        x: 3.5
        y: 0
        z: 30.0
      - !Vector3
        x: 10.0
        y: 0
        z: 25.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 2
        z: 4.0
      - !Vector3
        x: 7.0
        y: 2
        z: 6
      - !Vector3
        x: 6
        y: 2
        z: 4.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 25.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 2
        z: 4.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 25.0
      - !Vector3
        x: 30.0
        y: 0
        z: 25.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 2
        z: 4.0
      - !Vector3
        x: 6
        y: 2
        z: 4.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 36.5
        y: 0
        z: 25.0
      - !Vector3
        x: 36.5
        y: 0
        z: 30.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 2
        z: 4.0
      - !Vector3
        x: 7.0
        y: 2
        z: 6
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 3.5
        y: 0
        z: 36.5
      - !Vector3
        x: 10.0
        y: 0
        z: 36.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 2
        z: 7.0
      - !Vector3
        x: 6
        y: 2
        z: 7.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 36.5
      - !Vector3
        x: 20.0
        y: 0
        z: 36.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 2
        z: 7.0
      - !Vector3
        x: 6
        y: 2
        z: 7.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 36.5
      - !Vector3
        x: 30.0
        y: 0
        z: 36.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 2
        z: 7.0
      - !Vector3
        x: 6
        y: 2
        z: 7.0
    - !Item
      colors: []
      name: Wall
      positions:
      - !Vector3
        x: 36.5
        y: 0
        z: 36.5
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 2
        z: 7.0
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 35.0
        y: 2
        z: 35.0
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 15.0
        y: 2
        z: 15.0
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 5.0
        y: 2
        z: 5.0
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20
        y: 0
        z: 20
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 40
        y: 0
        z: 40
    t: 500
