!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 8.0
        y: 0
        z: 8.0
      - !Vector3
        x: 8.0
        y: 0
        z: 16.0
      - !Vector3
        x: 8.0
        y: 0
        z: 24.0
      - !Vector3
        x: 8.0
        y: 0
        z: 32.0
      - !Vector3
        x: 16.0
        y: 0
        z: 8.0
      - !Vector3
        x: 16.0
        y: 0
        z: 16.0
      - !Vector3
        x: 16.0
        y: 0
        z: 24.0
      - !Vector3
        x: 16.0
        y: 0
        z: 32.0
      - !Vector3
        x: 24.0
        y: 0
        z: 8.0
      - !Vector3
        x: 24.0
        y: 0
        z: 16.0
      - !Vector3
        x: 24.0
        y: 0
        z: 24.0
      - !Vector3
        x: 24.0
        y: 0
        z: 32.0
      - !Vector3
        x: 32.0
        y: 0
        z: 8.0
      - !Vector3
        x: 32.0
        y: 0
        z: 16.0
      - !Vector3
        x: 32.0
        y: 0
        z: 24.0
      - !Vector3
        x: 32.0
        y: 0
        z: 32.0
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 8.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 8.0
      - !Vector3
        x: 24.0
        y: 0
        z: 3.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 16.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 16.0
      - !Vector3
        x: 32.0
        y: 0
        z: 12.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 8.0
        y: 0
        z: 20.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 16.0
        y: 0
        z: 20.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 24.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 24.0
      - !Vector3
        x: 32.0
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 8.0
        y: 0
        z: 28.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 16.0
        y: 0
        z: 28.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 32.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 8.0
        y: 0
        z: 37.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 24.0
        y: 0
        z: 37.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 1.7135367453192754
        y: 0
        z: 21.923670936404065
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 14.010335406318465
        y: 0
        z: 10.537613711021795
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 3.21957699904378
        y: 0
        z: 38.04544296568782
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
