!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 2.5
        y: 0
        z: 2.5
      - !Vector3
        x: 8.0
        y: 0
        z: 2.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 5.0
      - !Vector3
        x: 6
        y: 2
        z: 5.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 2.5
      - !Vector3
        x: 16.0
        y: 0
        z: 2.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 5.0
      - !Vector3
        x: 6
        y: 2
        z: 5.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 2.5
      - !Vector3
        x: 20.0
        y: 0
        z: 8.0
      - !Vector3
        x: 24.0
        y: 0
        z: 2.5
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 5.0
      - !Vector3
        x: 2.0
        y: 2
        z: 6
      - !Vector3
        x: 6
        y: 2
        z: 5.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 2.5
      - !Vector3
        x: 28.0
        y: 0
        z: 8.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 5.0
      - !Vector3
        x: 2.0
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 37.5
        y: 0
        z: 2.5
      - !Vector3
        x: 37.5
        y: 0
        z: 8.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 5.0
      - !Vector3
        x: 5.0
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 2.5
        y: 0
        z: 12.0
      - !Vector3
        x: 2.5
        y: 0
        z: 16.0
      - !Vector3
        x: 8.0
        y: 0
        z: 12.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 2.0
      - !Vector3
        x: 5.0
        y: 2
        z: 6
      - !Vector3
        x: 6
        y: 2
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 12.0
      - !Vector3
        x: 12.0
        y: 0
        z: 16.0
      - !Vector3
        x: 16.0
        y: 0
        z: 12.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 2.0
      - !Vector3
        x: 2.0
        y: 2
        z: 6
      - !Vector3
        x: 6
        y: 2
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 12.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 12.0
      - !Vector3
        x: 28.0
        y: 0
        z: 16.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 2.0
      - !Vector3
        x: 2.0
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 37.5
        y: 0
        z: 12.0
      - !Vector3
        x: 37.5
        y: 0
        z: 16.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 2.0
      - !Vector3
        x: 5.0
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 2.5
        y: 0
        z: 20.0
      - !Vector3
        x: 2.5
        y: 0
        z: 24.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 2.0
      - !Vector3
        x: 5.0
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 20.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 20.0
      - !Vector3
        x: 20.0
        y: 0
        z: 24.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 2.0
      - !Vector3
        x: 2.0
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 20.0
      - !Vector3
        x: 32.0
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 2.0
      - !Vector3
        x: 6
        y: 2
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 37.5
        y: 0
        z: 20.0
      - !Vector3
        x: 37.5
        y: 0
        z: 24.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 2.0
      - !Vector3
        x: 5.0
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 2.5
        y: 0
        z: 28.0
      - !Vector3
        x: 8.0
        y: 0
        z: 28.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 2.0
      - !Vector3
        x: 6
        y: 2
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 28.0
      - !Vector3
        x: 16.0
        y: 0
        z: 28.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 2.0
      - !Vector3
        x: 6
        y: 2
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 28.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 28.0
      - !Vector3
        x: 28.0
        y: 0
        z: 32.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 2.0
      - !Vector3
        x: 2.0
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 37.5
        y: 0
        z: 28.0
      - !Vector3
        x: 37.5
        y: 0
        z: 32.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 2.0
      - !Vector3
        x: 5.0
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 2.5
        y: 0
        z: 37.5
      - !Vector3
        x: 8.0
        y: 0
        z: 37.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 5.0
      - !Vector3
        x: 6
        y: 2
        z: 5.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 37.5
      - !Vector3
        x: 16.0
        y: 0
        z: 37.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 5.0
      - !Vector3
        x: 6
        y: 2
        z: 5.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 37.5
      - !Vector3
        x: 24.0
        y: 0
        z: 37.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 5.0
      - !Vector3
        x: 6
        y: 2
        z: 5.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 37.5
      - !Vector3
        x: 32.0
        y: 0
        z: 37.5
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 2
        z: 5.0
      - !Vector3
        x: 6
        y: 2
        z: 5.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 37.5
        y: 0
        z: 37.5
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 5.0
        y: 2
        z: 5.0
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 20.0
        y: 2
        z: 20.0
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 4.0
        y: 2
        z: 4.0
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 36.0
        y: 2
        z: 36.0
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20
        y: 0
        z: 20
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 40
        y: 0
        z: 40
    t: 500
