!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 8.0
        y: 0
        z: 8.0
      - !Vector3
        x: 8.0
        y: 0
        z: 16.0
      - !Vector3
        x: 8.0
        y: 0
        z: 24.0
      - !Vector3
        x: 8.0
        y: 0
        z: 32.0
      - !Vector3
        x: 16.0
        y: 0
        z: 8.0
      - !Vector3
        x: 16.0
        y: 0
        z: 16.0
      - !Vector3
        x: 16.0
        y: 0
        z: 24.0
      - !Vector3
        x: 16.0
        y: 0
        z: 32.0
      - !Vector3
        x: 24.0
        y: 0
        z: 8.0
      - !Vector3
        x: 24.0
        y: 0
        z: 16.0
      - !Vector3
        x: 24.0
        y: 0
        z: 24.0
      - !Vector3
        x: 24.0
        y: 0
        z: 32.0
      - !Vector3
        x: 32.0
        y: 0
        z: 8.0
      - !Vector3
        x: 32.0
        y: 0
        z: 16.0
      - !Vector3
        x: 32.0
        y: 0
        z: 24.0
      - !Vector3
        x: 32.0
        y: 0
        z: 32.0
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 3.75
        y: 0
        z: 3.75
      - !Vector3
        x: 3.75
        y: 0
        z: 8.0
      - !Vector3
        x: 8.0
        y: 0
        z: 3.75
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.5
      - !Vector3
        x: 7.5
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 7.5
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 3.75
      - !Vector3
        x: 16.0
        y: 0
        z: 3.75
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.5
      - !Vector3
        x: 1
        y: 5
        z: 7.5
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 3.75
      - !Vector3
        x: 20.0
        y: 0
        z: 8.0
      - !Vector3
        x: 24.0
        y: 0
        z: 3.75
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.5
      - !Vector3
        x: 7.0
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 7.5
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 3.75
      - !Vector3
        x: 32.0
        y: 0
        z: 3.75
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.5
      - !Vector3
        x: 1
        y: 5
        z: 7.5
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 36.25
        y: 0
        z: 3.75
      - !Vector3
        x: 36.25
        y: 0
        z: 8.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.5
      - !Vector3
        x: 7.5
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 3.75
        y: 0
        z: 12.0
      - !Vector3
        x: 3.75
        y: 0
        z: 16.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.0
      - !Vector3
        x: 7.5
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 12.0
      - !Vector3
        x: 12.0
        y: 0
        z: 16.0
      - !Vector3
        x: 16.0
        y: 0
        z: 12.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.0
      - !Vector3
        x: 7.0
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 7.0
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 12.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.0
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 12.0
      - !Vector3
        x: 28.0
        y: 0
        z: 16.0
      - !Vector3
        x: 32.0
        y: 0
        z: 12.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.0
      - !Vector3
        x: 7.0
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 7.0
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 36.25
        y: 0
        z: 12.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.0
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 3.75
        y: 0
        z: 20.0
      - !Vector3
        x: 3.75
        y: 0
        z: 24.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.0
      - !Vector3
        x: 7.5
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 20.0
      - !Vector3
        x: 12.0
        y: 0
        z: 24.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.0
      - !Vector3
        x: 7.0
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 20.0
      - !Vector3
        x: 20.0
        y: 0
        z: 24.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.0
      - !Vector3
        x: 7.0
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 20.0
      - !Vector3
        x: 32.0
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.0
      - !Vector3
        x: 1
        y: 5
        z: 7.0
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 36.25
        y: 0
        z: 20.0
      - !Vector3
        x: 36.25
        y: 0
        z: 24.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.0
      - !Vector3
        x: 7.5
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 3.75
        y: 0
        z: 28.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.0
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 28.0
      - !Vector3
        x: 12.0
        y: 0
        z: 32.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.0
      - !Vector3
        x: 7.0
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 28.0
      - !Vector3
        x: 20.0
        y: 0
        z: 32.0
      - !Vector3
        x: 24.0
        y: 0
        z: 28.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.0
      - !Vector3
        x: 7.0
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 7.0
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 28.0
      - !Vector3
        x: 28.0
        y: 0
        z: 32.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.0
      - !Vector3
        x: 7.0
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 36.25
        y: 0
        z: 28.0
      - !Vector3
        x: 36.25
        y: 0
        z: 32.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.0
      - !Vector3
        x: 7.5
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 3.75
        y: 0
        z: 36.25
      - !Vector3
        x: 8.0
        y: 0
        z: 36.25
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.5
      - !Vector3
        x: 1
        y: 5
        z: 7.5
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 12.0
        y: 0
        z: 36.25
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.5
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 36.25
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.5
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 28.0
        y: 0
        z: 36.25
      - !Vector3
        x: 32.0
        y: 0
        z: 36.25
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.0
        y: 5
        z: 7.5
      - !Vector3
        x: 1
        y: 5
        z: 7.5
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 36.25
        y: 0
        z: 36.25
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7.5
        y: 5
        z: 7.5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
