!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 13.333333333333334
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 26.666666666666668
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 13.333333333333334
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 26.666666666666668
      rotations:
      - 0
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
      - !Vector3
        x: 1
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 6.416666666666667
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 12.833333333333334
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 20.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 12.333333333333334
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 26.666666666666668
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 12.333333333333334
        y: 5
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions:
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 33.583333333333336
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 12.833333333333334
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
