!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 10.0
        y: 0
        z: 10.0
      - !Vector3
        x: 10.0
        y: 0
        z: 20.0
      - !Vector3
        x: 10.0
        y: 0
        z: 30.0
      - !Vector3
        x: 20.0
        y: 0
        z: 10.0
      - !Vector3
        x: 20.0
        y: 0
        z: 20.0
      - !Vector3
        x: 20.0
        y: 0
        z: 30.0
      - !Vector3
        x: 30.0
        y: 0
        z: 10.0
      - !Vector3
        x: 30.0
        y: 0
        z: 20.0
      - !Vector3
        x: 30.0
        y: 0
        z: 30.0
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 4.0
        y: 0
        z: 4.0
      - !Vector3
        x: 4.0
        y: 0
        z: 10.0
      - !Vector3
        x: 10.0
        y: 0
        z: 4.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 8.0
      - !Vector3
        x: 8.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 4.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 4.0
      - !Vector3
        x: 25.0
        y: 0
        z: 10.0
      - !Vector3
        x: 30.0
        y: 0
        z: 4.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 8.0
      - !Vector3
        x: 6.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 36.0
        y: 0
        z: 4.0
      - !Vector3
        x: 36.0
        y: 0
        z: 10.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 8.0
      - !Vector3
        x: 8.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 4.0
        y: 0
        z: 15.0
      - !Vector3
        x: 10.0
        y: 0
        z: 15.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 6.0
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 15.0
      - !Vector3
        x: 20.0
        y: 0
        z: 15.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 6.0
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 15.0
      - !Vector3
        x: 25.0
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 6.0
      - !Vector3
        x: 6.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 36.0
        y: 0
        z: 15.0
      - !Vector3
        x: 36.0
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 6.0
      - !Vector3
        x: 8.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 4.0
        y: 0
        z: 25.0
      - !Vector3
        x: 4.0
        y: 0
        z: 30.0
      - !Vector3
        x: 10.0
        y: 0
        z: 25.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 6.0
      - !Vector3
        x: 8.0
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 25.0
      - !Vector3
        x: 15.0
        y: 0
        z: 30.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 6.0
      - !Vector3
        x: 6.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 25.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 6.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 36.0
        y: 0
        z: 25.0
      - !Vector3
        x: 36.0
        y: 0
        z: 30.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 6.0
      - !Vector3
        x: 8.0
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 4.0
        y: 0
        z: 36.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 36.0
      - !Vector3
        x: 20.0
        y: 0
        z: 36.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 8.0
      - !Vector3
        x: 4
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 25.0
        y: 0
        z: 36.0
      - !Vector3
        x: 30.0
        y: 0
        z: 36.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 6.0
        y: 5
        z: 8.0
      - !Vector3
        x: 4
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 36.0
        y: 0
        z: 36.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 8.0
        y: 5
        z: 8.0
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 9.18341300136601
        y: 0
        z: 36.27099703493595
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 26.642498549185095
        y: 0
        z: 28.73875790264094
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 21.109050631938224
        y: 0
        z: 3.9323855491507933
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
