!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 13.333333333333334
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 26.666666666666668
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 13.333333333333334
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 26.666666666666668
      rotations:
      - 0
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 5.666666666666667
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 11.333333333333334
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 13.333333333333334
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 9.333333333333334
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 20.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 9.333333333333334
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 34.333333333333336
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 11.333333333333334
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 33.960126998135145
        y: 0
        z: 10.001964172349009
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 26.654441830561773
        y: 0
        z: 4.364341134511648
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 5.432048604308056
        y: 0
        z: 31.97653111651293
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
