!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 13.333333333333334
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 26.666666666666668
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 13.333333333333334
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 26.666666666666668
      rotations:
      - 0
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 5.666666666666667
        y: 0
        z: 13.333333333333334
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 11.333333333333334
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 13.333333333333334
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 9.333333333333334
        y: 5
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 26.666666666666668
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 9.333333333333334
        y: 5
        z: 4
      - !Vector3
        x: 4
        y: 5
        z: 9.333333333333334
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 27.748325322370032
        y: 0
        z: 3.7918751211788226
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 20.536498217150303
        y: 0
        z: 38.183358199378205
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 34.983014624465966
        y: 0
        z: 25.42843070937501
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
