!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 5.166666666666668
        y: 0
        z: 5.166666666666668
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 5.166666666666668
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 10.333333333333332
        y: 2
        z: 10.333333333333332
      - !Vector3
        x: 6
        y: 2
        z: 10.333333333333332
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 5.166666666666668
      - !Vector3
        x: 20.0
        y: 0
        z: 13.333333333333334
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 5.166666666666668
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.333333333333333
        y: 2
        z: 10.333333333333332
      - !Vector3
        x: 7.333333333333333
        y: 2
        z: 6
      - !Vector3
        x: 6
        y: 2
        z: 10.333333333333332
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 34.833333333333336
        y: 0
        z: 5.166666666666668
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 10.333333333333332
        y: 2
        z: 10.333333333333332
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 5.166666666666668
        y: 0
        z: 20.0
      - !Vector3
        x: 5.166666666666668
        y: 0
        z: 26.666666666666668
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 20.0
      rotations:
      - 0
      - 0
      - 0
      sizes:
      - !Vector3
        x: 10.333333333333332
        y: 2
        z: 7.333333333333333
      - !Vector3
        x: 10.333333333333332
        y: 2
        z: 6
      - !Vector3
        x: 6
        y: 2
        z: 7.333333333333333
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 20.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7.333333333333333
        y: 2
        z: 7.333333333333333
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 34.833333333333336
        y: 0
        z: 20.0
      - !Vector3
        x: 34.833333333333336
        y: 0
        z: 26.666666666666668
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 10.333333333333332
        y: 2
        z: 7.333333333333333
      - !Vector3
        x: 10.333333333333332
        y: 2
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 5.166666666666668
        y: 0
        z: 34.833333333333336
      - !Vector3
        x: 13.333333333333334
        y: 0
        z: 34.833333333333336
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 10.333333333333332
        y: 2
        z: 10.333333333333332
      - !Vector3
        x: 6
        y: 2
        z: 10.333333333333332
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 20.0
        y: 0
        z: 34.833333333333336
      - !Vector3
        x: 26.666666666666668
        y: 0
        z: 34.833333333333336
      rotations:
      - 0
      - 0
      sizes:
      - !Vector3
        x: 7.333333333333333
        y: 2
        z: 10.333333333333332
      - !Vector3
        x: 6
        y: 2
        z: 10.333333333333332
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 34.833333333333336
        y: 0
        z: 34.833333333333336
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 10.333333333333332
        y: 2
        z: 10.333333333333332
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 33.333333333333336
        y: 2
        z: 20.0
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 6.666666666666666
        y: 2
        z: 33.333333333333336
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 20.0
        y: 2
        z: 6.666666666666666
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 20
        y: 0
        z: 20
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 40
        y: 0
        z: 40
    t: 500
