!ArenaConfig
arenas:
  0: !Arena
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 1, z: 20}
    - !Item
      name: Wall
      sizes:
      - !Vector3 {x: 5, y: 1, z: 5}
      rotations:
      - 0
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
    - !Item
      name: Ramp
      sizes:
      - !Vector3 {x: 5, y: 1, z: 5}
      rotations:
      - 0
      positions:
      - !Vector3 {x: 20, y: 0, z: 25}
