!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Wall
      sizes:
      - !Vector3 {x: 10, y: 1, z: 1}
      - !Vector3 {x: 10, y: 1, z: 1}
      - !Vector3 {x: 10, y: 1, z: 1}
      - !Vector3 {x: 10, y: 1, z: 1}
