01_food:
  # # ### just one goal
  GoodGoal_size05.yaml:
    threshold: -0.5
    n_tests: 5
  GoodGoal_size1.yaml:
    threshold: 0
    n_tests: 5
  GoodGoal_size2.yaml:
    threshold: 0
    n_tests: 5
  GoodGoal_size3.yaml:
    threshold: 0
    n_tests: 5
  GoodGoal_size4.yaml:
    threshold: 0
    n_tests: 5
  GoodGoal_size5.yaml:
    threshold: 0
    n_tests: 5
  GoodGoalMulti_size05.yaml:
    threshold: -0.5
    n_tests: 5
  GoodGoalMulti_size1.yaml:
    threshold: 0
    n_tests: 5
  GoodGoalMulti_size2.yaml:
    threshold: 0
    n_tests: 5
  GoodGoalMulti_size3.yaml:
    threshold: 0
    n_tests: 5
  GoodGoalMulti_size4.yaml:
    threshold: 0
    n_tests: 5
  GoodGoalMulti_size5.yaml:
    threshold: 0
    n_tests: 5
  ### bouncing goals
  GoodGoalBounce_size05.yaml:
    threshold: -0.5
    n_tests: 5
  GoodGoalBounce_size1.yaml:
    threshold: 0
    n_tests: 5
  GoodGoalBounce_size5.yaml:
    threshold: 0
    n_tests: 5
  GoodGoalMultiBounce_size05.yaml:
    threshold: -0.5
    n_tests: 5
  GoodGoalMultiBounce_size1.yaml:
    threshold: 0
    n_tests: 5
  GoodGoalMultiBounce_size5.yaml:
    threshold: 0
    n_tests: 5
  ### bad goals labyrinths
  Labyrinth15_GoodGoal.yaml:
    threshold: 0
    n_tests: 5
  Labyrinth15_GoodGoalMulti.yaml:
    threshold: 0
    n_tests: 5
  Labyrinth30_GoodGoal.yaml:
    threshold: 0
    n_tests: 5
  Labyrinth30_GoodGoalMulti.yaml:
    threshold: 0
    n_tests: 5
  Labyrinth30_GoodGoalMulti4.yaml:
    threshold: 3
    n_tests: 5
    partial_threshold: 1
  ### moving labyrinth
  MovingLabyrinth5_GoodGoal.yaml:
    threshold: 0
    n_tests: 5
  MovingLabyrinth10_GoodGoal.yaml:
    threshold: 0
    n_tests: 5
  MovingLabyrinth15_GoodGoal.yaml:
    threshold: 0
    n_tests: 5
  MovingLabyrinth5_GoodGoalMulti.yaml:
    threshold: 0
    n_tests: 5
  MovingLabyrinth10_GoodGoalMulti.yaml:
    threshold: 0
    n_tests: 5
  MovingLabyrinth15_GoodGoalMulti.yaml:
    threshold: 0
    n_tests: 5
  ### Red house
  RedHouse_1.yaml:
    threshold: 0
    n_tests: 1
  RedHouse_2.yaml:
    threshold: 0
    n_tests: 1
  RedHouse_3.yaml:
    threshold: 0
    n_tests: 1
  RedHouse_4.yaml:
    threshold: 0
    n_tests: 1
  RedHouse_5.yaml:
    threshold: 0
    n_tests: 1
  RedHouse_6.yaml:
    threshold: 0
    n_tests: 1
  RedHouse_7.yaml:
    threshold: 0
    n_tests: 1
  RedHouse_8.yaml:
    threshold: 0
    n_tests: 1
  ### Dead coming
  DeadComing_1.yaml:
    threshold: 0
    n_tests: 1
  DeadComing_2.yaml:
    threshold: 0
    n_tests: 1
  DeadComing_3.yaml:
    threshold: 0
    n_tests: 1
  DeadComing_4.yaml:
    threshold: 0
    n_tests: 1
  ### Hiding goal
  HidingGoal_1.yaml:
    threshold: 0
    n_tests: 1
  HidingGoal_2.yaml:
    threshold: 0
    n_tests: 1
  HidingGoal_3.yaml:
    threshold: 0
    n_tests: 1
  ### Red wall
  RedWall_1.yaml:
    threshold: 0
    n_tests: 1
  RedWall_2.yaml:
    threshold: 0
    n_tests: 1
  RedWall_3.yaml:
    threshold: 0
    n_tests: 1
  RedWall_4.yaml:
    threshold: 0
    n_tests: 1
  RedWall_5.yaml:
    threshold: 0
    n_tests: 1
  RedWall_6.yaml:
    threshold: 0
    n_tests: 1
  RedWall_7.yaml:
    threshold: 0
    n_tests: 1
  RedRandomWall.yaml:
    threshold: 0
    n_tests: 5
  ### Yellow over green
  YellowOverGreen_1.yaml:
    threshold: 1
    n_tests: 1
  YellowOverGreen_2.yaml:
    threshold: 1
    n_tests: 1
  YellowOverGreen_3.yaml:
    threshold: 1
    n_tests: 1
  YellowOverGreen_4.yaml:
    threshold: 1
    n_tests: 1
  YellowOverGreen_5.yaml:
    threshold: 1
    n_tests: 1
  YellowOverGreen_6.yaml:
    threshold: 1
    n_tests: 1
  YellowOverGreen_7.yaml:
    threshold: 1
    n_tests: 1
  YellowOverGreen_8.yaml:
    threshold: 2
    n_tests: 1
  YellowOverGreen_9.yaml:
    threshold: 1
    n_tests: 1
  YellowOverGreen_10.yaml:
    threshold: 2
    n_tests: 1
  YellowOverGreen_11.yaml:
    threshold: 1
    n_tests: 1
02_preferences:
  ## Green sizes
  Green_sizes12_1.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_2.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_3.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_4.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_5.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_6.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_7.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_8.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_9.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_10.yaml:
    threshold: 1
    n_tests: 1
  Green_sizes12_11.yaml:
    threshold: 1
    n_tests: 1
  ## Yellow over green behind the window
  YellowOverGreen_1.yaml:
    threshold: 2
    n_tests: 1
  YellowOverGreen_2.yaml:
    threshold: 1
    n_tests: 1
  YellowOverGreen_3.yaml:
    threshold: 2
    n_tests: 1
  YellowOverGreen_4.yaml:
    threshold: 1
    n_tests: 1
03_obstacles:
  Obstacles.yaml:
    threshold: 0
    n_tests: 10
  objectManipulation.yaml:
    threshold: 0
    n_tests: 10
  ### goal on platform
  Goal_on_platform_1.yaml:
    threshold: 0
    n_tests: 5
  Goal_on_platform_2.yaml:
    threshold: 0
    n_tests: 5
  Goal_on_platform_3.yaml:
    threshold: 0
    n_tests: 5
  Goal_on_platform_4.yaml:
    threshold: 0
    n_tests: 5
  Goal_on_platform_5.yaml:
    threshold: 0
    n_tests: 5
  Goal_on_platform_6.yaml:
    threshold: 0
    n_tests: 5
  ### wall with ramp
  Wall_with_ramp_1.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_ramp_2.yaml:
    threshold: 0
    n_tests: 1
  ### wall with obstacle
  Wall_with_obstacle_1.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_obstacle_2.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_obstacle_3.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_obstacle_4.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_obstacle_5.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_obstacle_6.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_obstacle_7.yaml:
    threshold: 0
    n_tests: 1
  ### wall with tunnel
  Wall_with_tunnel_1.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_tunnel_2.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_tunnel_3.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_tunnel_4.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_tunnel_5.yaml:
    threshold: 0
    n_tests: 1
  Wall_with_tunnel_6.yaml:
    threshold: 0
    n_tests: 1
  ## wall in the middle
  Wall_middle.yaml:
    threshold: 0
    n_tests: 1
  WallTransparent_middle_1.yaml:
    threshold: 0
    n_tests: 1
  WallTransparent_middle_2.yaml:
    threshold: 0
    n_tests: 1
  WallTransparent_middle_3.yaml:
    threshold: 0
    n_tests: 1
  ### Navigation
  Navigation_1.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_2.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_3.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_4.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_5.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_6.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_7.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_8.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  ### Navigation on platform
  Navigation_on_platform_1.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_platform_2.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_platform_3.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_platform_4.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  ### Navigation on splitted arena
  Navigation_on_splitted_arena_1.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_splitted_arena_2.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_splitted_arena_3.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_splitted_arena_4.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_splitted_arena_5.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
04_avoidance:
  ### CenterMoat
  CenterMoat_1.yaml:
    threshold: 0
    n_tests: 1
  CenterMoat_2.yaml:
    threshold: 0
    n_tests: 1
  CenterMoat_3.yaml:
    threshold: 0
    n_tests: 1
  CenterMoat_4.yaml:
    threshold: 0
    n_tests: 1
  ### Ring
  Ring_1.yaml:
    threshold: 0
    n_tests: 1
  Ring_2.yaml:
    threshold: 0
    n_tests: 1
  Ring_3.yaml:
    threshold: 0
    n_tests: 1
  Ring_4.yaml:
    threshold: 0
    n_tests: 1
  ### RingBlocked
  RingBlocked_1.yaml:
    threshold: 0
    n_tests: 1
  RingBlocked_2.yaml:
    threshold: 0
    n_tests: 1
  RingBlocked_3.yaml:
    threshold: 0
    n_tests: 1
  RingBlocked_4.yaml:
    threshold: 0
    n_tests: 1
  ### CenterMoat
  CenterMoatBlocked_1.yaml:
    threshold: 0
    n_tests: 1
  CenterMoatBlocked_2.yaml:
    threshold: 0
    n_tests: 1
  CenterMoatBlocked_3.yaml:
    threshold: 0
    n_tests: 1
  CenterMoatBlocked_4.yaml:
    threshold: 0
    n_tests: 1
  ### Chessboards
  ChessBoard_1.yaml:
    threshold: 0
    n_tests: 5
  ChessBoard_2.yaml:
    threshold: 0
    n_tests: 5
  ChessBoard_3.yaml:
    threshold: 0
    n_tests: 5
  ChessBoard_4.yaml:
    threshold: 0
    n_tests: 5
  ### Labyrinth
  Labyrinth_1.yaml:
    threshold: 0
    n_tests: 5
  Labyrinth_2.yaml:
    threshold: 0
    n_tests: 5
  Labyrinth_3.yaml:
    threshold: 0
    n_tests: 5
  Labyrinth_4.yaml:
    threshold: 0
    n_tests: 5
  ### Goal_in_HotZone
  Goal_in_HotZone_1.yaml:
    threshold: 0
    n_tests: 1
  Goal_in_HotZone_2.yaml:
    threshold: 0
    n_tests: 1
  Goal_in_HotZone_3.yaml:
    threshold: 0
    n_tests: 1
  ### Goal_in_DeathZone
  Goal_in_DeathZone_1.yaml:
    threshold: -1
    n_tests: 1
  Goal_in_DeathZone_2.yaml:
    threshold: -1
    n_tests: 1
  Goal_in_DeathZone_3.yaml:
    threshold: -1
    n_tests: 1
  Goal_in_DeathZone_4.yaml:
    threshold: 0
    n_tests: 1
  Goal_in_DeathZone_5.yaml:
    threshold: 0
    n_tests: 1
  Goal_in_DeathZone_6.yaml:
    threshold: 0
    n_tests: 1
  ### Goal_behind_HotZone
  Goal_behind_HotZone_1.yaml:
    threshold: -0.9
    n_tests: 1
  Goal_behind_HotZone_2.yaml:
    threshold: -0.9
    n_tests: 1
  Goal_behind_HotZone_3.yaml:
    threshold: -0.9
    n_tests: 1
  Goal_behind_HotZone_4.yaml:
    threshold: -0.9
    n_tests: 1
  Goal_behind_HotZone_5.yaml:
    threshold: -0.9
    n_tests: 1
05_spatial_reasoning:
  SpatialReasoning.yaml:
    threshold: 1
    n_tests: 10
    partial_threshold: 0
06_generalization:
  Generalization.yaml:
    threshold: 1
    n_tests: 10
    partial_threshold: 0
  ### navigation
  Navigation_1.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_2.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_3.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_4.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  ### goal on platform
  Goal_on_platform_1.yaml:
    threshold: 0
    n_tests: 5
  Goal_on_platform_2.yaml:
    threshold: 0
    n_tests: 5
  Goal_on_platform_3.yaml:
    threshold: 0
    n_tests: 5
  ### navigation on platform
  Navigation_on_platform_1.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_platform_2.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_platform_3.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
  Navigation_on_platform_4.yaml:
    threshold: 1
    n_tests: 5
    partial_threshold: 0
07_internal_memory:
  InternalMemory_1.yaml:
    threshold: 0
    n_tests: 5
  InternalMemory_2.yaml:
    threshold: 0
    n_tests: 5
  InternalMemory_3.yaml:
    threshold: 0
    n_tests: 5
  InternalMemory_4.yaml:
    threshold: 0
    n_tests: 5
  InternalMemory_5.yaml:
    threshold: 0
    n_tests: 5
  InternalMemory_6.yaml:
    threshold: 0
    n_tests: 5
  InternalMemory_7.yaml:
    threshold: 1
    n_tests: 5
  InternalMemory_8.yaml:
    threshold: 1
    n_tests: 5
  InternalMemory_9.yaml:
    threshold: 1
    n_tests: 5
  InternalMemory_10.yaml:
    threshold: 1
    n_tests: 5
09_advanced_preferences:
  forcedChoice_1.yaml:
    threshold: 0
    n_tests: 1
  forcedChoice_2.yaml:
    threshold: 0
    n_tests: 1
  forcedChoice_3.yaml:
    threshold: 0
    n_tests: 1
  forcedChoice_4.yaml:
    threshold: 0
    n_tests: 1
  forcedChoice_5.yaml:
    threshold: 1
    n_tests: 1
  ## Forced choice random
  forcedChoice_Random_1.yaml:
    threshold: 0
    n_tests: 5
  forcedChoice_Random_2.yaml:
    threshold: 0
    n_tests: 5
  forcedChoice_Random_3.yaml:
    threshold: 1
    n_tests: 5
  forcedChoice_Random_4.yaml:
    threshold: 3
    n_tests: 5
  forcedChoice_Random_5.yaml:
    threshold: 0
    n_tests: 5
  forcedChoice_Random_6.yaml:
    threshold: 0
    n_tests: 5
  forcedChoice_Random_7.yaml:
    threshold: 1
    n_tests: 5
  forcedChoice_Random_8.yaml:
    threshold: 3
    n_tests: 5
10_causal_reasoning:
  Bridge_1.yaml:
    threshold: 0
    n_tests: 1
  Bridge_2.yaml:
    threshold: 0
    n_tests: 1
  Bridge_3.yaml:
    threshold: 0
    n_tests: 1
  DoubleBridge_1.yaml:
    threshold: 0
    n_tests: 1
  DoubleBridge_2.yaml:
    threshold: 1
    n_tests: 1
    partial_threshold: 0
  Jump_1.yaml:
    threshold: 0
    n_tests: 1
  Push_1.yaml:
    threshold: 0
    n_tests: 1
  Push_2.yaml:
    threshold: 0
    n_tests: 1
  SuperBridge_1.yaml:
    threshold: 0
    n_tests: 1
  SuperBridge_2.yaml:
    threshold: 0
    n_tests: 1
  SuperBridge_3.yaml:
    threshold: 0
    n_tests: 1
  Burning_food_1.yaml:
    threshold: 0
    n_tests: 1
  Burning_food_2.yaml:
    threshold: 0
    n_tests: 1
  Burning_food_3.yaml:
    threshold: 0
    n_tests: 1
  Burning_food_4.yaml:
    threshold: 0
    n_tests: 1
  Burning_food_5.yaml:
    threshold: 0
    n_tests: 5
  Burning_food_6.yaml:
    threshold: 0
    n_tests: 5
  Break_the_RedWall_1.yaml:
    threshold: 1
    n_tests: 5
  Break_the_RedWall_2.yaml:
    threshold: 1
    n_tests: 5
  Break_the_RedWall_3.yaml:
    threshold: 1
    n_tests: 5
  Food_on_top_of_movable_1.yaml:
    threshold: 0
    n_tests: 2
  Food_on_top_of_movable_2.yaml:
    threshold: 0
    n_tests: 2
  Food_on_top_of_movable_3.yaml:
    threshold: 0
    n_tests: 2
  Goal_on_platform_1.yaml:
    threshold: 0
    n_tests: 2