!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 8.25
        y: 0
        z: 18
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 16.5
        y: 7.0
        z: 1.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 30.75
        y: 0
        z: 18
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 18.5
        y: 3.0
        z: 4.0
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 29.384087493335358
        y: 0
        z: 14.482210713520884
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 12.57083103353376
        y: 0
        z: 25.758656631061516
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 13.5866773189378
        y: 0
        z: 6.999527976669329
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 5
        z: 2
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 5
        z: 3
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 1
        z: 2
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 6.0
    t: 500
