!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 21
        y: 0
        z: 8.75
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 8.0
        z: 17.5
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 21
        y: 0
        z: 30.25
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 3.0
        z: 19.5
    - !Item
      colors: []
      name: Cardbox2
      positions:
      - !Vector3
        x: 21
        y: 0
        z: 19.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 2.5
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 30.81537621418119
        y: 0
        z: 5.765433882268505
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 15.557092886657152
        y: 0
        z: 14.183012662934155
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 8.366924715780389
        y: 0
        z: 29.676033013364105
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 1.0
        z: 1
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 4.0
    t: 500
