!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 16.338502454192835
        y: 0
        z: 30.43120732188678
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6
        y: 1.0
        z: 5
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 16.338502454192835
        y: 0
        z: 26.87683727889266
      rotations:
      - 180.0
      sizes:
      - !Vector3
        x: 6
        y: 1.0
        z: 2.1087400859882486
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 16.338502454192835
        y: 1.0
        z: 30.43120732188678
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 10.034605589010802
        y: 0
        z: 30.090385732134493
      rotations:
      - 182.0
      sizes:
      - !Vector3
        x: 3
        y: 6
        z: 4
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 10.034605589010802
        y: 0
        z: 30.090385732134493
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 7.6937455510657555
        y: 0
        z: 12.327774806301068
      rotations:
      - 154.0
      sizes:
      - !Vector3
        x: 2
        y: 8
        z: 4
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 24.977342477514835
        y: 0
        z: 6.425245583994913
      rotations:
      - 55.0
      sizes:
      - !Vector3
        x: 4
        y: 7
        z: 3
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 26.937145338484804
        y: 0
        z: 25.978034361693368
      rotations:
      - 133.0
      sizes:
      - !Vector3
        x: 8
        y: 3
        z: 8
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 4.876185860831711
        y: 0
        z: 19.3431838134834
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 6.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 1
        z: 9
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 6
        z: 9
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 5.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 7
        y: 2
        z: 4
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 7
        z: 2
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 9
        y: 9
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 1
        z: 7
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 3
        z: 7
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
