!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: Cardbox1
      positions:
      - !Vector3
        x: 28.82177950607229
        y: 0
        z: 30.96972734390897
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 2.0
        z: 4
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 28.82177950607229
        y: 2.0
        z: 30.96972734390897
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions:
      - !Vector3
        x: 31.022872844238726
        y: 0
        z: 8.011150911698053
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 5
        z: 6
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 31.022872844238726
        y: 0
        z: 8.011150911698053
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 17.263780041693295
        y: 0
        z: 31.86680532406155
      rotations:
      - 29.0
      sizes:
      - !Vector3
        x: 5
        y: 2
        z: 3
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 14.952883000356824
        y: 0
        z: 13.693463141293236
      rotations:
      - 227.0
      sizes:
      - !Vector3
        x: 9
        y: 6
        z: 2
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 31.430872058171907
        y: 0
        z: 19.616559397658676
      rotations:
      - 288.0
      sizes:
      - !Vector3
        x: 3
        y: 2
        z: 2
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 1.5730701936135927
        y: 0
        z: 20.467453037773122
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 7
        y: 5
        z: 3
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 3
        z: 3
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 1
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 6.0
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 6
        z: 5
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 6.0
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
