!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 6.839411559583473
        y: 0
        z: 14.583678675611784
      rotations:
      - 192.0
      sizes:
      - !Vector3
        x: 2
        y: 7
        z: 2
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 6.839411559583473
        y: 0
        z: 14.583678675611784
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 15.167895476726278
        y: 0
        z: 37.50669939492588
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 31.090594365355322
        y: 0
        z: 13.752917099486284
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7
        y: 2.0
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 31.090594365355322
        y: 0
        z: 8.878974269715123
      rotations:
      - 180.0
      sizes:
      - !Vector3
        x: 7
        y: 2.0
        z: 3.7478856595423222
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 17.119638915294725
        y: 0
        z: 7.473615161316094
      rotations:
      - 129.0
      sizes:
      - !Vector3
        x: 4
        y: 2
        z: 2
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 11.489572382602864
        y: 0
        z: 19.509273968222306
      rotations:
      - 154.0
      sizes:
      - !Vector3
        x: 7
        y: 8
        z: 7
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 27.873648541548125
        y: 0
        z: 23.912725721587677
      rotations:
      - 108.0
      sizes:
      - !Vector3
        x: 2
        y: 4
        z: 6
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 35.84677565203394
        y: 0
        z: 17.828685710767246
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 1
        z: 8
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 9
        y: 2
        z: 5
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 8
        z: 5
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 8.0
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 4
        z: 1
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 1
        z: 7
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 3
        z: 2
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 4
        z: 8
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
