!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 10.0
        y: 0
        z: 29
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 20.0
        y: 7.0
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 31.0
        y: 0
        z: 29
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 18.0
        y: 6.0
        z: 3.0
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 12.837862241990186
        y: 0
        z: 33.324838288284575
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 11.331031579892635
        y: 0
        z: 27.064838574981575
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 35.86077251580508
        y: 0
        z: 17.327185356780504
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 3
        z: 2
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 2
        z: 2
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 8.0
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 9.0
    t: 500
