!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 17.571727562759307
        y: 0
        z: 20.13239197348203
      rotations:
      - 122.0
      sizes:
      - !Vector3
        x: 9
        y: 3
        z: 2
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 17.571727562759307
        y: 0
        z: 20.13239197348203
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 17.797713094799153
        y: 0
        z: 38.51799030014452
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 13.901488250609713
        y: 0
        z: 13.021891749857856
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 5
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 17.092918390334255
        y: 0
        z: 13.021891749857856
      rotations:
      - 90.0
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 2.382860279449087
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 13.853481328737091
        y: 0
        z: 30.984544386472987
      rotations:
      - 90.0
      sizes:
      - !Vector3
        x: 6
        y: 4
        z: 5
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 26.149522272838826
        y: 0
        z: 27.838757024181852
      rotations:
      - 346.0
      sizes:
      - !Vector3
        x: 9
        y: 4
        z: 5
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 23.979531088419417
        y: 0
        z: 11.515339539775468
      rotations:
      - 200.0
      sizes:
      - !Vector3
        x: 8
        y: 8
        z: 3
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 30.662508565754543
        y: 0
        z: 23.34721400149673
      rotations:
      - 164.0
      sizes:
      - !Vector3
        x: 2
        y: 5
        z: 2
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 27.089305586212042
        y: 0
        z: 20.5987369777707
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 7
        z: 7
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 3
        z: 1
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 7.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 9
        y: 8
        z: 5
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 4
        z: 2
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 6
        z: 5
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 6
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 6
        z: 5
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
