!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions:
      - !Vector3
        x: 10.430736039436214
        y: 0
        z: 32.55026584551704
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 5
        z: 6
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 10.430736039436214
        y: 0
        z: 32.55026584551704
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 28.86258527957055
        y: 0
        z: 10.26800884811271
      rotations:
      - 62.0
      sizes:
      - !Vector3
        x: 3
        y: 4
        z: 6
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 28.86258527957055
        y: 0
        z: 10.26800884811271
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 8.760990295261424
        y: 0
        z: 9.433238000062385
      rotations:
      - 278.0
      sizes:
      - !Vector3
        x: 5
        y: 9
        z: 5
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 27.365964306555924
        y: 0
        z: 31.37929746782793
      rotations:
      - 192.0
      sizes:
      - !Vector3
        x: 5
        y: 4
        z: 3
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 21.91008900432652
        y: 0
        z: 12.768443909167733
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 7.0
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 4.0
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 3
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 7.0
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 6.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 6
        z: 2
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 9
        y: 3
        z: 7
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 8.0
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 3
        z: 2
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
