!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 20
        y: 0
        z: 8.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3.0
        y: 7.0
        z: 16.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 20
        y: 0
        z: 30.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1.0
        y: 3.0
        z: 20.0
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 30.323023829677904
        y: 0
        z: 7.695808899542108
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 5.4347439490032965
        y: 0
        z: 13.911301968052824
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 36.61746398717667
        y: 0
        z: 14.709429729792646
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 1.0
        z: 2
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 1.0
        z: 3
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 2
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 3.0
    t: 500
