!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 21
        y: 0
        z: 8.25
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 6.0
        z: 16.5
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 21
        y: 0
        z: 30.75
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 4.0
        z: 18.5
    - !Item
      colors: []
      name: Cardbox1
      positions:
      - !Vector3
        x: 21
        y: 0
        z: 19.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3
        y: 2.0
        z: 4.5
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 15.761158162506273
        y: 0
        z: 32.31917931260983
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 12.389687364888024
        y: 0
        z: 3.3370879172347108
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 31.083634653926737
        y: 0
        z: 4.849997119976345
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 3
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 1.0
        z: 3
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 2.0
        z: 5
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 4.0
    t: 500
