!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 30.201263894559478
        y: 0
        z: 12.324593784691405
      rotations:
      - 36.0
      sizes:
      - !Vector3
        x: 4
        y: 4
        z: 6
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 30.201263894559478
        y: 0
        z: 12.324593784691405
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions:
      - !Vector3
        x: 11.069055776258892
        y: 0
        z: 31.627508696496317
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 4
        z: 3
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 11.069055776258892
        y: 4
        z: 31.627508696496317
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 16.20610419059415
        y: 0
        z: 22.554599710648354
      rotations:
      - 257.0
      sizes:
      - !Vector3
        x: 6
        y: 7
        z: 8
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 4.266954005989135
        y: 0
        z: 30.0067714174235
      rotations:
      - 94.0
      sizes:
      - !Vector3
        x: 3
        y: 3
        z: 2
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 35.88195526315564
        y: 0
        z: 4.711424247941711
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 3.0
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 2
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 7
        y: 3
        z: 4
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 5.0
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 1
        z: 3
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 3.0
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
