!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 34.61107973789366
        y: 0
        z: 21.50995293813769
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions:
      - !Vector3
        x: 21.915531110600394
        y: 0
        z: 20.8586117338539
      rotations: []
      sizes:
      - !Vector3
        x: 9
        y: 9
        z: 9
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 21.915531110600394
        y: 0
        z: 20.8586117338539
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 11.73959035734262
        y: 0
        z: 22.291684479470376
      rotations:
      - 199.0
      sizes:
      - !Vector3
        x: 7
        y: 2
        z: 2
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 27.818044013295545
        y: 0
        z: 9.6275152131351
      rotations:
      - 355.0
      sizes:
      - !Vector3
        x: 3
        y: 4
        z: 4
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 28.86822488299009
        y: 0
        z: 15.300035409558992
      rotations:
      - 196.0
      sizes:
      - !Vector3
        x: 5
        y: 9
        z: 2
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 10.623276142281707
        y: 0
        z: 9.182965671316884
      rotations:
      - 230.0
      sizes:
      - !Vector3
        x: 7
        y: 4
        z: 6
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 33.21254001748818
        y: 0
        z: 30.37064908333611
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 9
        y: 8
        z: 2
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1.0
        z: 5
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 1.0
        z: 5
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 7
        y: 5
        z: 7
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 9
        y: 2
        z: 1
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 7
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 4
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 2.0
        z: 2
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
