!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: Cardbox1
      positions:
      - !Vector3
        x: 9.49624735173264
        y: 0
        z: 28.115397155150706
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 4
        z: 3
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 9.49624735173264
        y: 4
        z: 28.115397155150706
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 25.858035553381157
        y: 0
        z: 21.76985846744057
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 7
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 25.858035553381157
        y: 0
        z: 26.988779661427966
      rotations:
      - 0.0
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 3.437842387974791
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 25.858035553381157
        y: 2.0
        z: 21.76985846744057
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 29.592664003854825
        y: 0
        z: 32.383975252495276
      rotations:
      - 324.0
      sizes:
      - !Vector3
        x: 6
        y: 9
        z: 6
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 17.272378841339908
        y: 0
        z: 13.078966139261471
      rotations:
      - 253.0
      sizes:
      - !Vector3
        x: 7
        y: 7
        z: 2
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 8.273533636965205
        y: 0
        z: 16.295732224815367
      rotations:
      - 71.0
      sizes:
      - !Vector3
        x: 3
        y: 4
        z: 6
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 5.687551396022613
        y: 0
        z: 17.763817516363062
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 8
        z: 8
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 5
        z: 2
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 4
        z: 7
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 5
        z: 1
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 7
        y: 3
        z: 6
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 2
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 4
        z: 2
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
