!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions:
      - !Vector3
        x: 24.156659092365203
        y: 0
        z: 18.94131448624855
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 3
        z: 9
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 24.156659092365203
        y: 0
        z: 18.94131448624855
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 26.510230006662272
        y: 0
        z: 38.488579937617544
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 20.92035621530882
        y: 0
        z: 32.2659520869078
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6
        y: 2.0
        z: 5
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 25.34142693063054
        y: 0
        z: 32.2659520869078
      rotations:
      - 90.0
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 2.8421414306434354
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 15.770084309344792
        y: 0
        z: 26.687042004690944
      rotations:
      - 323.0
      sizes:
      - !Vector3
        x: 6
        y: 3
        z: 4
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 15.724407632329502
        y: 0
        z: 15.987023504968914
      rotations:
      - 260.0
      sizes:
      - !Vector3
        x: 3
        y: 7
        z: 9
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 21.681370311875362
        y: 0
        z: 20.513021787398994
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 3
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 9
        z: 6
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 5
        z: 8
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 6
        z: 7
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 8
        z: 6
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
