!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 12.722099035159854
        y: 0
        z: 21.472274196652958
      rotations:
      - 10.0
      sizes:
      - !Vector3
        x: 3
        y: 9
        z: 5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 12.722099035159854
        y: 0
        z: 21.472274196652958
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions:
      - !Vector3
        x: 16.748525684813252
        y: 0
        z: 10.97416259643553
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 7
        z: 8
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 16.748525684813252
        y: 0
        z: 10.97416259643553
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 29.015100299795222
        y: 0
        z: 23.466640767153173
      rotations:
      - 344.0
      sizes:
      - !Vector3
        x: 8
        y: 6
        z: 5
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 20.819437629786496
        y: 0
        z: 20.095138543617765
      rotations:
      - 48.0
      sizes:
      - !Vector3
        x: 2
        y: 7
        z: 7
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 18.810757721650667
        y: 0
        z: 30.6179381557294
      rotations:
      - 270.0
      sizes:
      - !Vector3
        x: 5
        y: 6
        z: 6
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 27.17247422314913
        y: 0
        z: 15.05947210475304
      rotations:
      - 145.0
      sizes:
      - !Vector3
        x: 6
        y: 5
        z: 8
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 32.83711913661058
        y: 0
        z: 3.6684524628656963
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 7
        z: 7
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 4.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 2
        z: 7
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 4.0
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 3
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 2
        z: 5
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 1
        z: 5
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
