!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 18.665529433167713
        y: 0
        z: 32.09870287013288
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 22.139953583150536
        y: 0
        z: 36.599576329667194
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 12.84503376083028
        y: 0
        z: 25.633665004456475
      rotations:
      - 181.0
      sizes:
      - !Vector3
        x: 3
        y: 5
        z: 3
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 25.213159481730564
        y: 0
        z: 18.590479171101567
      rotations:
      - 275.0
      sizes:
      - !Vector3
        x: 7
        y: 4
        z: 3
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 30.0808052444223
        y: 0
        z: 23.143976911604867
      rotations:
      - 264.0
      sizes:
      - !Vector3
        x: 5
        y: 8
        z: 5
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 8.610532499343968
        y: 0
        z: 27.848018277498145
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 8
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 4
        z: 9
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 5
        z: 5
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 9
        y: 8
        z: 7
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 5
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 4.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 8
        z: 3
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
