!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 5.5
        y: 0
        z: 22
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 11.0
        y: 9.0
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 27.5
        y: 0
        z: 22
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 25.0
        y: 2.0
        z: 4.0
    - !Item
      colors: []
      name: Cardbox2
      positions:
      - !Vector3
        x: 13.0
        y: 0
        z: 22
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3.5
        y: 1.0
        z: 1
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 12.993750157970371
        y: 0
        z: 33.561187877338924
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 4.349723632789065
        y: 0
        z: 18.831872339542162
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 15.132472171819892
        y: 0
        z: 29.660732495294223
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 2.0
        z: 3
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 2.0
        z: 5
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 7.0
    t: 500
