!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 16
        y: 0
        z: 8.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 8.0
        z: 16.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 16
        y: 0
        z: 30.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3.0
        y: 5.0
        z: 20.0
    - !Item
      colors: []
      name: Cardbox1
      positions:
      - !Vector3
        x: 16
        y: 0
        z: 18.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 3
        z: 3.5
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 23.198004927574722
        y: 0
        z: 4.618131962162457
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 36.951728269950436
        y: 0
        z: 37.56803728579352
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 21.33711667029932
        y: 0
        z: 21.261262432431543
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 4
        z: 2
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 1
        z: 5
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 8.0
    t: 500
