!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions:
      - !Vector3
        x: 28.899204326507803
        y: 0
        z: 30.723825939482193
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 3
        z: 3
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 28.899204326507803
        y: 0
        z: 30.723825939482193
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 21.1056542896265
        y: 0
        z: 13.984788260730026
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 5
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 16.647055821690884
        y: 0
        z: 13.984788260730026
      rotations:
      - 270.0
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 4.917196935871228
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 21.1056542896265
        y: 2.0
        z: 13.984788260730026
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 11.071889780314034
        y: 0
        z: 28.415916139395115
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7
        y: 1.0
        z: 5
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 6.782426092100653
        y: 0
        z: 28.415916139395115
      rotations:
      - 270.0
      sizes:
      - !Vector3
        x: 5
        y: 1.0
        z: 1.5789273764267628
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 19.381506143425128
        y: 0
        z: 24.738385887764263
      rotations:
      - 182.0
      sizes:
      - !Vector3
        x: 6
        y: 5
        z: 3
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 13.534459099255203
        y: 0
        z: 17.73940768157762
      rotations:
      - 118.0
      sizes:
      - !Vector3
        x: 2
        y: 4
        z: 2
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 32.20740489673844
        y: 0
        z: 25.972690477753765
      rotations:
      - 109.0
      sizes:
      - !Vector3
        x: 2
        y: 7
        z: 4
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 27.68671055566905
        y: 0
        z: 16.60567755991889
      rotations:
      - 200.0
      sizes:
      - !Vector3
        x: 6
        y: 8
        z: 2
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 1.0619845417423983
        y: 0
        z: 26.513193022039893
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 4.0
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 8
        z: 9
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 8
        z: 3
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 7
        z: 1
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 9
        z: 3
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 1.0
        z: 2
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 4
        z: 8
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 7
        z: 4
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 4
        z: 7
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
