!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions:
      - !Vector3
        x: 13.61811405357368
        y: 0
        z: 12.367827909232723
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 3
        z: 5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 13.61811405357368
        y: 0
        z: 12.367827909232723
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 15.764629784994655
        y: 0
        z: 17.56155222716453
      rotations:
      - 58.0
      sizes:
      - !Vector3
        x: 2
        y: 3
        z: 3
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 15.764629784994655
        y: 0
        z: 17.56155222716453
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: HotZone
      positions:
      - !Vector3
        x: 9.822299431067483
        y: 0
        z: 24.555570620884808
      rotations:
      - 320.0
      sizes:
      - !Vector3
        x: 4
        y: 6
        z: 7
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 28.194823778745295
        y: 0
        z: 27.22000255247498
      rotations:
      - 158.0
      sizes:
      - !Vector3
        x: 5
        y: 9
        z: 7
    - !Item
      colors: []
      name: DeathZone
      positions:
      - !Vector3
        x: 24.49032960382028
        y: 0
        z: 18.73170703434103
      rotations:
      - 126.0
      sizes:
      - !Vector3
        x: 3
        y: 4
        z: 7
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 6.274626869591742
        y: 0
        z: 28.189420754615526
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 3
        z: 8
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 4.0
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 3
        z: 9
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 6
        z: 1
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 8
        z: 2
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 3.0
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
