!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 12.25
        y: 0
        z: 10
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 24.5
        y: 2.0
        z: 2.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: DeathZone
      positions:
      - !Vector3
        x: 34.75
        y: 0
        z: 10
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 10.5
        y: 7.0
        z: 1.0
    - !Item
      colors: []
      name: Cardbox1
      positions:
      - !Vector3
        x: 27.0
        y: 0
        z: 10
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.5
        y: 1
        z: 2
    - !Item
      colors: []
      name: Agent
      positions:
      - !Vector3
        x: 8.314776851967032
        y: 0
        z: 5.493221135193808
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 1.2692541016602519
        y: 0
        z: 22.854627995488958
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 31.883649798773554
        y: 0
        z: 24.21365712074154
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 2
        z: 2
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 4
        z: 4
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 3.0
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 4.0
    t: 500
