!ArenaConfig
arenas:
  0: !Arena # Random DeathZones squares, ring of DeathZones in the border, more variability on start and end
    t: 500
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: -1, y: 0, z: 38}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 0, z: 2}
      rotations:
      - 0
    # 6 squares of size 5 at random x positions
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: -1, y: 0, z: 16}
      - !Vector3 {x: -1, y: 0, z: 16}
      - !Vector3 {x: -1, y: 0, z: 16}
      - !Vector3 {x: -1, y: 0, z: 16}
      - !Vector3 {x: -1, y: 0, z: 16}
      - !Vector3 {x: -1, y: 0, z: 16}
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: -1, y: 0, z: 24}
      - !Vector3 {x: -1, y: 0, z: 24}
      - !Vector3 {x: -1, y: 0, z: 24}
      - !Vector3 {x: -1, y: 0, z: 24}
      - !Vector3 {x: -1, y: 0, z: 24}
      - !Vector3 {x: -1, y: 0, z: 24}
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: -1, y: 0, z: 34}
      - !Vector3 {x: -1, y: 0, z: 34}
      - !Vector3 {x: -1, y: 0, z: 34}
      - !Vector3 {x: -1, y: 0, z: 34}
      - !Vector3 {x: -1, y: 0, z: 34}
      - !Vector3 {x: -1, y: 0, z: 34}
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: -1, y: 0, z: 6}
      - !Vector3 {x: -1, y: 0, z: 6}
      - !Vector3 {x: -1, y: 0, z: 6}
      - !Vector3 {x: -1, y: 0, z: 6}
      - !Vector3 {x: -1, y: 0, z: 6}
      - !Vector3 {x: -1, y: 0, z: 6}
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 1, y: 0, z: 20}
      - !Vector3 {x: 39, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 0, z: 34}
      - !Vector3 {x: 2, y: 0, z: 34}
      rotations:
      - 0
      - 0