!ArenaConfig
arenas:
  0: !Arena # Random DeathZones squares, ring of DeathZone in the border
    t: 500
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 0, z: 36}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 4}
      rotations:
      - 0
    # 6 squares of size 5 at random x positions
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: -1, y: 0, z: 20}
      - !Vector3 {x: -1, y: 0, z: 20}
      - !Vector3 {x: -1, y: 0, z: 20}
      - !Vector3 {x: -1, y: 0, z: 20}
      - !Vector3 {x: -1, y: 0, z: 20}
      - !Vector3 {x: -1, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: -1, y: 0, z: 30}
      - !Vector3 {x: -1, y: 0, z: 30}
      - !Vector3 {x: -1, y: 0, z: 30}
      - !Vector3 {x: -1, y: 0, z: 30}
      - !Vector3 {x: -1, y: 0, z: 30}
      - !Vector3 {x: -1, y: 0, z: 30}
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: -1, y: 0, z: 10}
      - !Vector3 {x: -1, y: 0, z: 10}
      - !Vector3 {x: -1, y: 0, z: 10}
      - !Vector3 {x: -1, y: 0, z: 10}
      - !Vector3 {x: -1, y: 0, z: 10}
      - !Vector3 {x: -1, y: 0, z: 10}
      sizes:
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      - !Vector3 {x: 20, y: 0, z: 39}
      - !Vector3 {x: 1, y: 0, z: 20}
      - !Vector3 {x: 39, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 40, y: 0, z: 2}
      - !Vector3 {x: 40, y: 0, z: 2}
      - !Vector3 {x: 2, y: 0, z: 40}
      - !Vector3 {x: 2, y: 0, z: 40}
      rotations:
      - 0
      - 0
      - 0
      - 0