!ArenaConfig
arenas:
  0: !Arena # One GoodGoal of size 1 at the other side of arena and 16 badgoals inbetween
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      - !Vector3 {x: 20, y: 0, z: 38}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 2}
      rotations:
      - 0
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 6, y: 0, z: 6}
      rotations:
      - 0