!ArenaConfig
arenas:
  0: !Arena # One GoodGoal of size 1 at the other side of arena and 16 badgoals inbetween
    t: 250
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 0, z: 36}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 2}
      rotations:
      - 0
    - !Item
      name: HotZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 36}
      sizes:
      - !Vector3 {x: 8, y: 0, z: 8}
      rotations:
      - 0