!ArenaConfig
arenas:
  0: !Arena # One GoodGoal of size 1 at the other side of arena and 16 badgoals inbetween
    t: 500
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 0, z: 30}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 10}
      rotations:
      - 0
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      - !Vector3 {x: 20, y: 0, z: 2.5}
      - !Vector3 {x: 20, y: 0, z: 37.5}
      - !Vector3 {x: 2.5, y: 0, z: 20}
      - !Vector3 {x: 37.5, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 15, y: 0, z: 15}
      - !Vector3 {x: 40, y: 0, z: 5}
      - !Vector3 {x: 40, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 40}
      - !Vector3 {x: 5, y: 0, z: 40}
      rotations:
      - 0
      - 0
      - 0
      - 0
      - 0