!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions:
      - !Vector3
        x: 6.5
        y: 0
        z: 15
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 13.0
        y: 6.0
        z: 1.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions:
      - !Vector3
        x: 28.5
        y: 0
        z: 15
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 23.0
        y: 3.0
        z: 4.0
    - !Item
      colors: []
      name: Cardbox1
      positions:
      - !Vector3
        x: 15.0
        y: 0
        z: 15
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3.5
        y: 1.0
        z: 5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 1.0
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 1
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 8.0
    t: 500
