!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 23
        y: 0
        z: 12.5
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3.0
        y: 6.0
        z: 25.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 23
        y: 0
        z: 33.5
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 2.0
        z: 13.0
    - !Item
      colors: []
      name: Cardbox2
      positions:
      - !Vector3
        x: 23
        y: 0
        z: 26.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3
        y: 3
        z: 1.5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 1
        z: 3
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 5
        z: 5
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 5
        z: 5
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 3.0
    t: 500
