!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions:
      - !Vector3
        x: 28.787116260043366
        y: 0
        z: 25.274262999705194
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 6
        z: 5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 28.787116260043366
        y: 0
        z: 25.274262999705194
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 8.0
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 3.0
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 4
        z: 3
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 2
        z: 2
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 4
        z: 5
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
