!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions:
      - !Vector3
        x: 27.436652262778104
        y: 0
        z: 10.742920752774808
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 4
        z: 8
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 27.436652262778104
        y: 0
        z: 10.742920752774808
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 19.095200114333636
        y: 0
        z: 10.34684435789785
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 5
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 15.31039401990444
        y: 0
        z: 10.34684435789785
      rotations:
      - 270.0
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 3.5696121888583954
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 19.095200114333636
        y: 2.0
        z: 10.34684435789785
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 5
        z: 4
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 7
        y: 7
        z: 4
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 7
        z: 6
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 6.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 3
        z: 4
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
