!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions:
      - !Vector3
        x: 9.0
        y: 0
        z: 18
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 18.0
        y: 2.0
        z: 4.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions:
      - !Vector3
        x: 30.0
        y: 0
        z: 18
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 20.0
        y: 7.0
        z: 4.0
    - !Item
      colors: []
      name: Cardbox2
      positions:
      - !Vector3
        x: 19.0
        y: 0
        z: 18
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1.5
        y: 4
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 5
        z: 4
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 2
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 7.0
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 9.0
    t: 500
