!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: Cardbox1
      positions:
      - !Vector3
        x: 25.970651963409317
        y: 0
        z: 11.032797308805826
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 2.0
        z: 5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 25.970651963409317
        y: 2.0
        z: 11.032797308805826
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 16.45099331715071
        y: 0
        z: 14.042204400939998
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 4
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 21.254538933353743
        y: 0
        z: 14.042204400939998
      rotations:
      - 90.0
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 5.607091232406063
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 16.45099331715071
        y: 2.0
        z: 14.042204400939998
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 4
        z: 8
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 2
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 8
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 3
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 5.0
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 6.0
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 1
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 5.0
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 2
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
