!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 9.5
        y: 0
        z: 14.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 19.0
        y: 3.0
        z: 1.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 30.5
        y: 0
        z: 26.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 19.0
        y: 3.0
        z: 1.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 14.0
        y: 0
        z: 30.5
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1.0
        y: 9.0
        z: 19.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 26.0
        y: 0
        z: 9.5
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1.0
        y: 9.0
        z: 19.0
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 5
        z: 3
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 3
        z: 5
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 5.0
    t: 500
