!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 13
        y: 0
        z: 9.25
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3.0
        y: 7.0
        z: 18.5
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 13
        y: 0
        z: 31.75
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3.0
        y: 2.0
        z: 16.5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 1.0
        z: 2
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1.0
        z: 2
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 9.0
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 8.0
    t: 500
