!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: Cardbox2
      positions:
      - !Vector3
        x: 37.18649641997291
        y: 0
        z: 8.335797236360156
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 2.0
        z: 2
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 37.18649641997291
        y: 2.0
        z: 8.335797236360156
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions:
      - !Vector3
        x: 20.654931044242783
        y: 0
        z: 33.11727396855696
      rotations: []
      sizes:
      - !Vector3
        x: 2
        y: 1.0
        z: 5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 20.654931044242783
        y: 1.0
        z: 33.11727396855696
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 21.666931112194398
        y: 0
        z: 18.15908121554748
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6
        y: 1.0
        z: 6
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 21.666931112194398
        y: 0
        z: 14.496834662758687
      rotations:
      - 180.0
      sizes:
      - !Vector3
        x: 6
        y: 1.0
        z: 1.324493105577589
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 8.0
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 2.0
        z: 3
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 5.0
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: CylinderTunnel
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 6
        z: 9
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 8
        y: 1
        z: 8
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 6.0
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 2.0
        z: 4
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
