!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors: []
      name: CylinderTunnelTransparent
      positions:
      - !Vector3
        x: 19.98303919567313
        y: 0
        z: 25.80129882906155
      rotations: []
      sizes:
      - !Vector3
        x: 7
        y: 6
        z: 6
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 19.98303919567313
        y: 0
        z: 25.80129882906155
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 26.14285828110515
        y: 0
        z: 18.19821490902361
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 6
        y: 2.0
        z: 4
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 26.14285828110515
        y: 0
        z: 14.721634293546137
      rotations:
      - 180.0
      sizes:
      - !Vector3
        x: 6
        y: 2.0
        z: 2.953161230954943
    - !Item
      colors: []
      name: GoodGoalMulti
      positions:
      - !Vector3
        x: 26.14285828110515
        y: 2.0
        z: 18.19821490902361
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 0
      name: Wall
      positions:
      - !Vector3
        x: 28.605586342425283
        y: 0
        z: 9.318754005325635
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 7
        y: 2.0
        z: 7
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions:
      - !Vector3
        x: 34.149203652243145
        y: 0
        z: 9.318754005325635
      rotations:
      - 90.0
      sizes:
      - !Vector3
        x: 7
        y: 2.0
        z: 4.08723461963573
    - !Item
      colors:
      - !RGB
        b: 255
        g: 0
        r: 255
      name: Ramp
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 5
        y: 3
        z: 4
    - !Item
      colors: []
      name: LObject2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 9.0
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 1.0
        z: 5
    - !Item
      colors: []
      name: WallTransparent
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 6
        y: 6
        z: 4
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 2.0
        z: 1
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 3.0
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    t: 500
