!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions:
      - !Vector3
        x: 28
        y: 0
        z: 12.75
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3.0
        y: 2.0
        z: 25.5
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: Wall
      positions:
      - !Vector3
        x: 28
        y: 0
        z: 35.25
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 3.0
        y: 3.0
        z: 9.5
    - !Item
      colors: []
      name: Cardbox1
      positions:
      - !Vector3
        x: 28
        y: 0
        z: 28.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 1
        y: 2
        z: 4.5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 4
        y: 4
        z: 5
    - !Item
      colors: []
      name: Cardbox1
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 3
        y: 5
        z: 5
    - !Item
      colors: []
      name: UObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 6.0
    t: 500
