!ArenaConfig
arenas:
  0: !Arena
    blackouts: []
    items:
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 14
        y: 0
        z: 4.25
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 4.0
        y: 5.0
        z: 8.5
    - !Item
      colors:
      - !RGB
        b: 153
        g: 153
        r: 153
      name: WallTransparent
      positions:
      - !Vector3
        x: 14
        y: 0
        z: 25.75
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 2.0
        y: 8.0
        z: 28.5
    - !Item
      colors: []
      name: Cardbox2
      positions:
      - !Vector3
        x: 14
        y: 0
        z: 10.0
      rotations:
      - 0
      sizes:
      - !Vector3
        x: 5
        y: 5
        z: 2.5
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: GoodGoalMulti
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: BadGoal
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 2
        z: 4
    - !Item
      colors: []
      name: Cardbox2
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: 1
        y: 1
        z: 1
    - !Item
      colors: []
      name: LObject
      positions: []
      rotations: []
      sizes:
      - !Vector3
        x: -1
        y: -1
        z: 3.0
    t: 500
