!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 40, y: 10, z: 2}
      - !Vector3 {x: 40, y: 10, z: 2}
      - !Vector3 {x: 2, y: 10, z: 36}
      - !Vector3 {x: 2, y: 10, z: 36}
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      - !Vector3 {x: 20, y: 0, z: 39}
      - !Vector3 {x: 1, y: 0, z: 20}
      - !Vector3 {x: 39, y: 0, z: 20}
      rotations: [0, 0, 0, 0]
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item # 4 BadGoal
      name: BadGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item # 4 Cardbox1
      name: Cardbox1
      rotations: [-1, -1, -1, -1]
