!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: -1, y: 3, z: 38}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 0, z: 2}
      rotations:
      - 0
    - !Item
      name: Wall
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 40, y: 1, z: 5}
      rotations:
      - 0
      positions:
      - !Vector3 {x: 20, y: 2, z: 37.5}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 5, y: 1, z: 5}
      rotations:
      - 180
      positions:
      - !Vector3 {x: -1, y: 2, z: 32.5}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 40, y: 1, z: 15}
      rotations:
      - 0
      positions:
      - !Vector3 {x: 20, y: 1, z: 32.5}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 5, y: 1, z: 5}
      rotations:
      - 180
      positions:
      - !Vector3 {x: -1, y: 1, z: 22.5}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 40, y: 1, z: 25}
      rotations:
      - 0
      positions:
      - !Vector3 {x: 20, y: 0, z: 27.5}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 5, y: 1, z: 5}
      rotations:
      - 180
      positions:
      - !Vector3 {x: -1, y: 0, z: 12.5}
