!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: LObject
      sizes:
      - !Vector3 {x: 5, y: 3, z: 5}
      - !Vector3 {x: 5, y: 3, z: 5}
      - !Vector3 {x: 5, y: 3, z: 5}
      - !Vector3 {x: 5, y: 3, z: 5}
    - !Item
      name: UObject
      sizes:
      - !Vector3 {x: 5, y: 3, z: 5}
      - !Vector3 {x: 5, y: 3, z: 5}
      - !Vector3 {x: 5, y: 3, z: 5}
      - !Vector3 {x: 5, y: 3, z: 5}
