!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 17, y: 5, z: 5}
      - !Vector3 {x: 17, y: 5, z: 5}
      rotations:
      - 0
      - 0
      positions:
      - !Vector3 {x: 8.5, y: 0, z: 20}
      - !Vector3 {x: 31.5, y: 0, z: 20}
    - !Item
      name: Cardbox1
      sizes:
      - !Vector3 {x: 5, y: 1.5, z: 5}
      rotations:
      - 180
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
    - !Item
      name: BadGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
    - !Item
      name: Cardbox1
      positions:
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: -1}
      sizes:
      - !Vector3 {x: 4, y: -1, z: 4}
      - !Vector3 {x: 4, y: -1, z: 4}
      - !Vector3 {x: 4, y: -1, z: 4}
      - !Vector3 {x: 4, y: -1, z: 4}
