!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 2}
      rotations:
      - 0
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 0, z: 38}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 34, y: 5, z: 2}
      rotations:
      - 0
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
