!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 2}
      rotations:
      - 0
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 0, z: 38}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 17, y: 5, z: 5}
      - !Vector3 {x: 17, y: 5, z: 5}
      rotations:
      - 0
      - 0
      positions:
      - !Vector3 {x: 8.5, y: 0, z: 20}
      - !Vector3 {x: 31.5, y: 0, z: 20}
    - !Item
      name: CylinderTunnel
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 5, y: 3, z: 15}
      rotations:
      - 180
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
