!ArenaConfig
arenas:
  0: !Arena
    t: 750
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 0.9, y: 0.9, z: 0.9}
      positions:
      - !Vector3 {x: 20, y: 1, z: 35}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 1, z: 5}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 20, y: 1, z: 16}
      - !Vector3 {x: 20, y: 1, z: 16}
      rotations:
      - 0
      - 0
      positions:
      - !Vector3 {x: 20, y: 0, z: 8}
      - !Vector3 {x: 20, y: 0, z: 32}
    - !Item
      name: Cardbox1
      sizes:
      - !Vector3 {x: 7, y: 1, z: 7}
      rotations:
      - 45
      positions:
      - !Vector3 {x: 15, y: 1, z: 7}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 5, y: 1, z: 5}
      - !Vector3 {x: 5, y: 1, z: 5}
      rotations:
      - 90
      - 270
      positions:
      - !Vector3 {x: 32.5, y: 0, z: 5}
      - !Vector3 {x: 7.5, y: 0, z: 5}