!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 5, y: 0, z: -1}
      - !Vector3 {x: 35, y: 0, z: -1}
      - !Vector3 {x: -1, y: 0, z: 5}
      - !Vector3 {x: -1, y: 0, z: 35}
    - !Item # 4 DeathZone
      name: DeathZone
      sizes:
      - !Vector3 {x: 1.5, y: -1, z: 24}
      - !Vector3 {x: 1.5, y: -1, z: 24}
      - !Vector3 {x: 24, y: -1, z: 1.5}
      - !Vector3 {x: 24, y: -1, z: 1.5}
      positions:
      - !Vector3 {x: 5, y: 0, z: 20}
      - !Vector3 {x: 35, y: 0, z: 20}
      - !Vector3 {x: 20, y: 0, z: 5}
      - !Vector3 {x: 20, y: 0, z: 35}
      rotations: [0, 0, 0, 0]
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
    - !Item # 4 Cardbox1
      name: Cardbox1
      sizes:
      - !Vector3 {x: 4, y: 1, z: 4}
      - !Vector3 {x: 4, y: 1, z: 4}
      - !Vector3 {x: 4, y: 1, z: 4}
      - !Vector3 {x: 4, y: 1, z: 4}
      - !Vector3 {x: 4, y: 1, z: 4}
      - !Vector3 {x: 4, y: 1, z: 4}
      - !Vector3 {x: 4, y: 1, z: 4}
      - !Vector3 {x: 4, y: 1, z: 4}