!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 1, z: 20}
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 1, z: 35}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 1, z: 5}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 20, y: 1, z: 10}
      - !Vector3 {x: 20, y: 1, z: 10}
      - !Vector3 {x: 20, y: 1, z: 10}
      rotations:
      - 0
      - 0
      - 0
      positions:
      - !Vector3 {x: 20, y: 0, z: 5}
      - !Vector3 {x: 20, y: 0, z: 35}
      - !Vector3 {x: 20, y: 0, z: 20}
    - !Item
      name: Cardbox1
      sizes:
      - !Vector3 {x: 4, y: 1, z: 4}
      - !Vector3 {x: 4, y: 1, z: 4}
      rotations:
      - 90
      - 90
      positions:
      - !Vector3 {x: 15, y: 1, z: 5}
      - !Vector3 {x: 25, y: 1, z: 20}
    - !Item
      name: Ramp
      colors:
      - !RGB {r: 255, g: 0, b: 255}
      - !RGB {r: 255, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 5, y: 1, z: 5}
      - !Vector3 {x: 5, y: 1, z: 5}
      rotations:
      - 90
      - 270
      positions:
      - !Vector3 {x: 32.5, y: 0, z: 5}
      - !Vector3 {x: 7.5, y: 0, z: 5}
