!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 20, y: 1, z: 20}
    - !Item
      name: Cardbox1
      sizes:
      - !Vector3 {x: 4, y: 1, z: 4}
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
