!ArenaConfig
arenas:
  0: !Arena
    t: 150
    blackouts: [50, 55, 75, 80, 100, 105, 125]
    items:
    - !Item
      name: WallTranparent
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
