!ArenaConfig
arenas:
  0: !Arena # One GoodGoal of size 1 at the other side of arena and 15 badgoals inbetween
    t: 500
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 2, y: 0, z: -1}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 38, y: 0, z: -1}
    - !Item
      name: BadGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 10, y: 0, z: -1}
      - !Vector3 {x: 15, y: 0, z: -1}
      - !Vector3 {x: 20, y: 0, z: -1}
      - !Vector3 {x: 25, y: 0, z: -1}
      - !Vector3 {x: 30, y: 0, z: -1}
    - !Item
      name: BadGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 10, y: 0, z: -1}
      - !Vector3 {x: 15, y: 0, z: -1}
      - !Vector3 {x: 20, y: 0, z: -1}
      - !Vector3 {x: 25, y: 0, z: -1}
      - !Vector3 {x: 30, y: 0, z: -1}