!ArenaConfig
arenas:
  0: !Arena # One GoodGoal of size 1 at the other side of arena and 16 badgoals inbetween
    t: 500
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 35, y: 0, z: 38}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 2}
      rotations:
      - 0
    - !Item
      name: BadGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 17.0, y: 0, z: 16}
      - !Vector3 {x: 20, y: 0, z: 16}
      - !Vector3 {x: 21.5, y: 0, z: 16}
      - !Vector3 {x: 23.0, y: 0, z: 16}
    - !Item
      name: BadGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 24.5, y: 0, z: 16}
      - !Vector3 {x: 26, y: 0, z: 16}
      - !Vector3 {x: 27.5, y: 0, z: 16}
      - !Vector3 {x: 29, y: 0, z: 16}
      - !Vector3 {x: 30.5, y: 0, z: 16}
    - !Item
      name: BadGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 32, y: 0, z: 16}
      - !Vector3 {x: 33.5, y: 0, z: 16}
      - !Vector3 {x: 35, y: 0, z: 16}
      - !Vector3 {x: 36.5, y: 0, z: 16}
      - !Vector3 {x: 38, y: 0, z: 16}
      - !Vector3 {x: 39.5, y: 0, z: 16}
    - !Item
      name: BadGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 15.5, y: 0, z: 16}
      - !Vector3 {x: 14, y: 0, z: 16}
      - !Vector3 {x: 12.5, y: 0, z: 16}
      - !Vector3 {x: 11, y: 0, z: 16}
      - !Vector3 {x: 9.5, y: 0, z: 16}
    - !Item
      name: BadGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
      - !Vector3 {x: 8, y: 0, z: 16}
      - !Vector3 {x: 6.5, y: 0, z: 16}
      - !Vector3 {x: 5, y: 0, z: 16}
      - !Vector3 {x: 3.5, y: 0, z: 16}
      - !Vector3 {x: 2, y: 0, z: 16}
      - !Vector3 {x: 1, y: 0, z: 16}